# 使用 OpenJDK 8 作为基础镜像
FROM openjdk:17-jdk-alpine

# 将项目的 jar 包复制到镜像中
COPY target/first-demo-0.0.1-SNAPSHOT.jar /app.jar

# 设置工作目录
WORKDIR /app/library-system

# 暴露应用运行的端口
EXPOSE 8080

# 启动应用
CMD ["java", "-jar", "/app.jar"]